name = "api-worker-cloudflare"
compatibility_date = "2024-09-09"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "database1"
database_id = "c1ed4c4d-cf86-48fb-bfb2-eb6a26bec9df"

[[kv_namespaces]]
binding = "KV"
id = "8c0e35e72b33492ca622c414a5252be4"

[triggers]
crons = [ "5 2 * * *"]